#!/bin/bash

uid=$(id -u)

if [ $uid -ne 0 ]
then
    echo "u must have root access"
    exit 1
fi

log_folder="/var/logs/shellscript-logs"
log_file=$(echo $0 | cut -d "." -f1)
timestamp=$(date +%Y-%m-%D-%H-%M-%S)
log_file_name="$log_folder/$log_file-$timestamp.log"

# echo "script was executed   at $timestamp"

# dnf list installed mysql >>$logfile_name

# if [$? -ne 0]
# then
# dnf install mysql -y
#     if [$? -ne 0]
#     then
#     echo "mysql was not installed" >>$log_file_name
#     exit 1
#     else
#     echo "mysql was installed"
#     fi
# else
# echo "mysql was already installed" >>$log_file_name
# fi


